# Generated by Django 4.1.7 on 2023-02-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='age',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
